In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from datetime import datetime
import matplotlib.ticker as ticker
import plotly.express as px
warnings.filterwarnings("ignore")

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/ncr_ride_bookings.csv')
df.head(5)

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.shape

(150000, 21)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  object
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  object
 3   Booking Status                     150000 non-null  object
 4   Customer ID                        150000 non-null  object
 5   Vehicle Type                       150000 non-null  object
 6   Pickup Location                    150000 non-null  object
 7   Drop Location                      150000 non-null  object
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   object
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   object
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    object
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  object
dtypes: float64(9), object(12)
memory usage: 24.0+ MB

In [ ]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

In [ ]:
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [ ]:
df['Reason for cancelling by Customer'] = df['Reason for cancelling by Customer'].fillna('Unknown')
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].fillna('Unknown')
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].fillna('Unknown')
df['Payment Method'] = df['Payment Method'].fillna('Unknown')
df['Avg VTAT'] = df['Avg VTAT'].fillna(0)
df['Avg CTAT'] = df['Avg CTAT'].fillna(0)
df['Cancelled Rides by Customer'] = df['Cancelled Rides by Customer'].fillna(0)
df['Cancelled Rides by Driver'] = df['Cancelled Rides by Driver'].fillna(0)
df['Incomplete Rides'] = df['Incomplete Rides'].fillna(0)
df['Booking Value'] = df['Booking Value'].fillna(0)
df['Ride Distance'] = df['Ride Distance'].fillna(0)
df['Driver Ratings'] = df['Driver Ratings'].fillna(0)
df['Customer Rating'] = df['Customer Rating'].fillna(0)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
df['Booking ID'] = df['Booking ID'].astype('string')
df['Booking Status'] = df['Booking Status'].astype('string')
df['Customer ID'] = df['Customer ID'].astype('string')
df['Vehicle Type'] = df['Vehicle Type'].astype('string')
df['Pickup Location'] = df['Pickup Location'].astype('string')
df['Drop Location'] = df['Drop Location'].astype('string')
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].astype('string')
df['Cancelled Rides by Customer'] = df['Cancelled Rides by Customer'].astype('int')
df['Reason for cancelling by Customer'] = df['Reason for cancelling by Customer'].astype('string')
df['Cancelled Rides by Driver'] = df['Cancelled Rides by Driver'].astype('int')
df['Driver Cancellation Reason'] = df['Driver Cancellation Reason'].astype('string')
df['Incomplete Rides'] = df['Incomplete Rides'].astype('int')
df['Incomplete Rides Reason'] = df['Incomplete Rides Reason'].astype('string')
df['Booking Value'] = df['Booking Value'].astype('int')
df['Payment Method'] = df['Payment Method'].astype('string')

In [ ]:
df.isnull().sum()

Date                                 0
Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Avg VTAT                             0
Avg CTAT                             0
Cancelled Rides by Customer          0
Reason for cancelling by Customer    0
Cancelled Rides by Driver            0
Driver Cancellation Reason           0
Incomplete Rides                     0
Incomplete Rides Reason              0
Booking Value                        0
Ride Distance                        0
Driver Ratings                       0
Customer Rating                      0
Payment Method                       0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  datetime64[ns]
 1   Time                               150000 non-null  object
 2   Booking ID                         150000 non-null  string
 3   Booking Status                     150000 non-null  string
 4   Customer ID                        150000 non-null  string
 5   Vehicle Type                       150000 non-null  string
 6   Pickup Location                    150000 non-null  string
 7   Drop Location                      150000 non-null  string
 8   Avg VTAT                           150000 non-null  float64
 9   Avg CTAT                           150000 non-null  float64
 10  Cancelled Rides by Customer        150000 non-null  int64
 11  Reason for cancelling by Customer  150000 non-null  string
 12  Cancelled Rides by Driver          150000 non-null  int64
 13  Driver Cancellation Reason         150000 non-null  string
 14  Incomplete Rides                   150000 non-null  int64
 15  Incomplete Rides Reason            150000 non-null  string
 16  Booking Value                      150000 non-null  int64
 17  Ride Distance                      150000 non-null  float64
 18  Driver Ratings                     150000 non-null  float64
 19  Customer Rating                    150000 non-null  float64
 20  Payment Method                     150000 non-null  string
dtypes: datetime64[ns](1), float64(5), int64(4), object(1), string(10)
memory usage: 24.0+ MB

In [ ]:
df['Booking Status'].unique()

<StringArray>
[      'No Driver Found',            'Incomplete',             'Completed',
   'Cancelled by Driver', 'Cancelled by Customer']
Length: 5, dtype: string

In [ ]:
total_rides = len(df) # number of rides
print(f"Number of Rides: {total_rides}")
rides_completed = (df['Booking Status'] == 'Completed').sum()
print(f"Number of Rides Completed: {rides_completed}")

Number of Rides: 150000
Number of Rides Completed: 93000

In [ ]:
sucess_rate_rides = (rides_completed/total_rides)*100
print(f"Sucess Rate: {sucess_rate_rides : .2f}%")

Sucess Rate:  62.00%

In [ ]:
avg_wait_time = np.mean(df['Avg VTAT'])
print(f"Average Wait Time: {avg_wait_time : .2f}")

Average Wait Time:  7.86

In [ ]:
completed_rides = df[df['Booking Status'] == 'Completed']
total_trip_duration = completed_rides['Avg CTAT'].sum()
avg_trip_duration = total_trip_duration / completed_rides.shape[0]
print(f"Average Trip Duration: {avg_trip_duration: .2f} minutes")

Average Trip Duration:  30.03 minutes

In [ ]:
completed_rides = df[df['Booking Status'] == 'Completed'] # Filtering just to the Completed Rides
total_ride_distance = completed_rides['Ride Distance'].sum() # Sum all's ride distance
avg_ride_distance = total_ride_distance / completed_rides.shape[0]
print(f"Average Ride Distance: {avg_ride_distance: .2f} minutes")

Average Ride Distance:  26.00 minutes

In [ ]:
# Calculating Cancellation Rate
rides_cancelled = (
    df['Cancelled Rides by Customer'].sum() +
    df['Cancelled Rides by Driver'].sum()
)  # number of cancelled rides
print(f"Number of Rides Cancelled: {rides_cancelled}")
cancellation_rate = (rides_cancelled/total_rides) * 100
print(f"Cancellation Rate: {cancellation_rate : .2f}%")

Number of Rides Cancelled: 37500
Cancellation Rate:  25.00%

In [ ]:
print(f"Cancellation Rate by Customer: {(df['Cancelled Rides by Customer'].sum()/total_rides)*100 : .2f}%")
print(f"Cancellation Rate by Driver: {(df['Cancelled Rides by Driver'].sum()/total_rides)*100 : .2f}%")

Cancellation Rate by Customer:  7.00%
Cancellation Rate by Driver:  18.00%

In [ ]:
df['First Usage'] = df.groupby('Customer ID')['Date'].transform('min') # Calculate First Use Date for each User
df['Last Usage'] = df.groupby('Customer ID')['Date'].transform('max') # Calculate Last Use Date for each User
df['Events After First Usage'] = df.groupby('Customer ID')['Date'].transform('count') # Identifying for each user if have more than 1 event

retained_users = df[df['Events After First Usage'] > 1]['Customer ID'].nunique() # Identifying retained users
first_users = df['Customer ID'].nunique() # Identifying the unique users

retention_rate = (retained_users / first_users) * 100 # Calculating Retention Rate
print(f"Retention Rate: {retention_rate: .2f}%")

Retention Rate:  0.81%

In [ ]:
# Calculating Monthly Active Users
df['Month'] = df['Date'].dt.to_period('M')
mau = df.groupby('Month')['Customer ID'].nunique()

print(f"Monthly Active Users - 2024 {mau}")

Monthly Active Users - 2024 Month
2024-01    12858
2024-02    11915
2024-03    12708
2024-04    12192
2024-05    12764
2024-06    12433
2024-07    12889
2024-08    12628
2024-09    12239
2024-10    12643
2024-11    12389
2024-12    12241
Freq: M, Name: Customer ID, dtype: int64

In [ ]:
# Calculate Usage Frequency per Month
month_rides = df.groupby(['Month'])['Booking ID'].count().reset_index(name='Ride Count') # Calculating rides per month
month_usage_frequency = month_rides.groupby('Month')['Ride Count'].mean()

print(f"Usage Frequency per Month {month_usage_frequency}")

Usage Frequency per Month Month
2024-01    12861.0
2024-02    11927.0
2024-03    12719.0
2024-04    12199.0
2024-05    12778.0
2024-06    12440.0
2024-07    12897.0
2024-08    12636.0
2024-09    12248.0
2024-10    12651.0
2024-11    12394.0
2024-12    12250.0
Freq: M, Name: Ride Count, dtype: float64

In [ ]:
# Calculate Average Revenue Per Ride
revenue_ride = df['Booking Value'].sum() / total_rides
print(f"Total Revenue: ${df['Booking Value'].sum():.2f}")
print(f"Total Revenue per Ride: ${revenue_ride:.2f}")

Total Revenue: $51846183.00
Total Revenue per Ride: $345.64

In [ ]:
# Calculate Average Revenue Per User
arpu = df['Booking Value'].sum() / df['Customer ID'].nunique()
print(f"ARPU (Average Revenue Per User): ${arpu:.2f}")

ARPU (Average Revenue Per User): $348.46

In [ ]:
# Calculate Driver Average Ratings
avg_ratings_driver = np.mean(df['Driver Ratings'])

print(f"Driver Average Rating: {avg_ratings_driver:.2f} / 5 stars")

Driver Average Rating: 2.62 / 5 stars

In [ ]:
# Calculate Customer Average Ratings
avg_ratings_customer = np.mean(df['Customer Rating'])

print(f"Customer Average Rating: {avg_ratings_customer:.2f} / 5 stars")

Customer Average Rating: 2.73 / 5 stars